### ISSUE TITLE
[Automation Kit - Private Preview Upgrade] Satellite Dataverse Plugin Upgrade

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-automation-kit#17]
### Describe the issue

Unable to upgrade private preview Satellite solution to September 2022 release 

### What component are you experiencing the issue with?

Other

### What solution version are you using?

Private Preview

### What app or flow are you having the issue with?

Satellite Dataverse Plugin

**Comment by jpad5** [comment]
Issue when upgrading Satellite from April release.
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/94862471/190780451-0c8d0d18-3981-4845-8cbc-295434521e2b.png)

Error Log:Error log: Plugin Assemblies import: FAILURE. Error: Plugin: AutoCoE.Extensibility.Plugins, Version=0.1.0.0, Culture=neutral, PublicKeyToken=65fb68c99935ed4d caused an exception.: PluginType [AutoCoE.Extensibility.Plugins.RPALogSyncToAzureLogAnalytics] not found in PluginAssembly [AutoCoE.Extensibility.Plugins, Version=0.1.0.0, Culture=neutral, PublicKeyToken=65fb68c99935ed4d] which has a total of [3] plugin/workflow activity types. Could be due to customization on same plugin through multiple solutions. PluginType tried to install conflicted with PluginType: AutoCoE.Extensibility.Plugins.RPALogSyncToAzureLogAnalytics (Id: 45cd7896-678f-4e8f-8a2e-90152df5862c) , PluginAssembly: AutoCoE.Extensibility.Plugins (Id: c8f4f22d-c74c-4d46-b206-8eee6f084e4f), Solution: AutomationCoESatellite (Id: 6ff2f158-aa87-4c2f-a4a6-009a9649bb59).

**Comment by jpad5** [comment]
Followed below steps to un-register for un-used actions in the AutoCOE Plugin: 
1.	RPALogSyncToAzureLogAnalytics
2.	DesktopFlowStaticAnalysis

 
1.	Download or install pluginregistrationtool through Package manager ( url: [NuGet Gallery | Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool 9.1.0.148](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool/9.1.0.148) or (https://docs.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget) 

2.	And run PluginregistrationTool.exe from c:\Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool.9.1.0.148\tools\PluginRegistration.exe

3.	Click on “Create New Connection” to connect to your satellite environment
4.	Provide necessary login credentials and select respective checkboxes as screen shot below 
5.	Click on “Login” button
6.	Select your COE satellite Environment and click on “Login” as screen shot below
7.	Your satellite environment will be loaded as below screen shot. It may take 5 secs to load.
8.	Expand the node “AutoCOE.Extenibility.Plugins” to show actions in that plugin.
9.	Select the plugin Action “AutoCOE.Extensibility.Plugins.DesktopFlowStaticAnalysis” and click on “Unregister”. And then Confirm ‘Yes’ to unregister.
10.	Select the plugin Action “AutoCOE.Extensibility.Plugins.RPALogSyncToAzureLogAnalytics” and click on “Unregister”. And then Confirm ‘Yes’ to unregister.
11.	After un-registering of above 2 actions, there will only be 3 actions.
12.	Close the pluginregistrationtool.exe window and try to import satellite solution in environment.

https://user-images.githubusercontent.com/94862471/190827083-52e4b0f2-19ef-4f7d-942e-a7a520d26dfc.mp4

**Comment by Grant-Archibald-MS** [comment]
Thanks @jpad5 I have included [Private Preview Upgrade](https://github.com/microsoft/powercat-automation-kit/blob/main/docs/private-preview-upgrade.md) in the docs section and added a note to the September 2022 release.

**Comment by Grant-Archibald-MS** [comment]
@KoteshMCGit closing the issue and changing status to done unless further testing identifies further updates to the upgrade notes above
