### ISSUE TITLE
[Automation Kit - QUESTION] No records on DLP App

### ISSUE THREAD

**Issue by suyash009** [microsoft/powercat-automation-kit#178]
### What is your question?

I am currently facing challenges in setting up the installation kit, especially the DLP app. I would like to setup the latest version of the kit which has the environment schedule view app. I have the environments ready with the system admin access. Can someone get in a short call and help me setup the kit. 

### What component is the question related to?

Other

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

DLP App

**Comment by KoteshMCGit** [comment]
Can you provide us with exact error details or screen shot, so we can help you to setup and configurations.

**Comment by suyash009** [comment]
I cannot see on any listing of the DLP app

**Comment by KoteshMCGit** [comment]
can we connect once to verify the issue.

Please ping me kmarram@microsoft.com in Teams (IST 11 AM to 9 PM only) to connect and verify the issue.

**Comment by suyash009** [comment]
I am not able to send mail via personal email. I have sent you a meeting invite form my corporate mail id.

**Comment by KoteshMCGit** [comment]
As per design of DLP Impact Analysis for PAD canvas app, it wont show any PAD flows by default. Based on your filter / search criteria, you will be shown with respective PAD flows.

As per our offline call, you have adjusted browser zoom and clicked on button "Search". later you got respective PAD flows based on your filters/search criteria.

can you please verify once and let me know if you have any issues. Otherwise we will treat this is closed.
