### ISSUE TITLE
[Automation - BUG] Cannot see PAD flow calling another PAD flow in Automation Kit Power BI Report

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powercat-automation-kit#210]
### Describe the issue

We have create a Reusable PAD flow which is called by another PAD flow and we cannot see any logs about the Reusable PAD flow in Power BI Report. 

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Create a Desktop Flow
2. Create a Second Desktop Flow
3. Call the 1st Desktop Flow from 2nd Desktop Flow
4. Run the Desktop Flow from Cloud Flow
5. Check the Power BI Report to see if the run history able to see of the 1st Desktop Flow

**Comment by KoteshMCGit** [comment]
As per your re-pro steps, I could not able to reproduce the scenario. Could you please let me know which page (like ROI, Goals and etc.,) you have verified in power bi dashboard. 

I assume that you have metered properly for cloud flow, which is calling pad flow 2.

**Comment by KoteshMCGit** [comment]
you can connect with me kmarram@microsoft.com in Team to do further analysis.

**Comment by KoteshMCGit** [comment]
As per your re-pro steps, we could not able to reproduce the scenario. Please find the below screenshot for the same.

Screenshot of both parent desktop flow and child desktop flow runs from single cloud flow in power automate.
![image](https://github.com/microsoft/powercat-automation-kit/assets/107620140/b3a0cd5a-c6be-42c1-ae46-dac90a0e3190)
 
screenshot of opening power bi dashboard from power automate.
![image](https://github.com/microsoft/powercat-automation-kit/assets/107620140/9351016a-544d-41c3-9ef1-56c262e3ec18)

screenshot of report in power bi desktop from Last Runs Page
![image](https://github.com/microsoft/powercat-automation-kit/assets/107620140/a77e55e4-c882-4b6a-827e-e53aa3719e86)

screenshot2 from power bi desktop from Last Runs Page
![image](https://github.com/microsoft/powercat-automation-kit/assets/107620140/18e00d7e-10d1-4aac-ba5c-33db31b38722)

As per our Analysis, this is expected behavior. if you observe any issue / different behavior, please let us know with respective screenshots. You can connect with me [kmarram@microsoft.com](mailto:kmarram@microsoft.com) in Team to do further analysis.
